[package]
name = "tinfoil-driver"
version = "0.1.0"
authors = ["Ron B <me@ronthecookie.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
xdotool = "0.0.2"
debouncr = "0.1.2"